name: Integración Continua (CI)

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias Backend
        working-directory: ServerDisacsur
        run: npm install

      - name: Instalar dependencias Frontend
        working-directory: frontenddisacsur
        run: npm install

      - name: Compilar Frontend
        working-directory: frontenddisacsur
        run: npm run build